import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {Package,ArrowUpRight,RotateCcw,Check} from 'lucide-react';
import {motion} from 'framer-motion';
import {useStore,money,track} from '../lib/store';
import {Action,Counter,Star} from './Elements';

export const BundleBuilder=({initialSize=4,compact=false})=>{
  const {products,content,addItem}=useStore();const configs=content.bundles.filter(b=>b.enabled);
  const [size,setSize]=useState(configs.find(b=>b.size===initialSize)?.size||configs[0]?.size||4),[selections,setSelections]=useState({});
  const bundle=configs.find(b=>b.size===size)||configs[0];
  const count=Object.values(selections).reduce((s,n)=>s+n,0),remaining=size-count;
  const available=products.filter(p=>p.category==='bhadang'&&p.available);
  const price=bundle?.price??Object.entries(selections).reduce((s,[id,q])=>s+(products.find(p=>p.id===id)?.price||0)*q,0);
  const chooseSize=n=>{setSize(n);setSelections({});track('bundle_builder_started',{size:n});};
  const change=(id,q)=>{if(q<0||count-(selections[id]||0)+q>size)return;if(bundle?.mix_match===false&&q>0&&Object.keys(selections).some(k=>k!==id)){setSelections({[id]:q});return;}setSelections(old=>{const copy={...old,[id]:q};if(q===0)delete copy[id];return copy;});};
  const add=()=>{if(count!==size)return;addItem({bundle_size:size,selections,quantity:1});track('bundle_completed',{size,selections,value:price});};
  if(!configs.length)return <div className="empty-state" data-testid="bundles-unavailable">Boxes are being updated. <Link to="/shop" data-testid="bundle-unavailable-shop">Explore individual packs</Link></div>;
  return <div className={`bundle-builder ${compact?'compact':''}`} data-testid="bundle-builder"><div className="box-visual"><div className="eyebrow">YOUR BOX. YOUR RULES.</div><h2>BUILD YOUR<br/><span>SANGLEY BOX.</span></h2><p>All your favourites. Or a new flavour affair.<br/>You call the crunch.</p><div className="box-stage" aria-label="Your selected packs" data-testid="box-visual"><div className="box-back"/><div className="box-packs">{Array.from({length:size}).map((_,i)=>{const ids=Object.entries(selections).flatMap(([id,n])=>Array(n).fill(id));const p=products.find(p=>p.id===ids[i]);return <motion.div className={`box-slot ${p?'filled':''}`} key={`${size}-${i}`} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:i*.035}}>{p?<img src={p.images[0]} alt={p.flavour}/>:<PlusSlot/>}</motion.div>;})}</div><div className="box-front"><span>SANGLEY</span><Star/><small>OPEN. SHARE. REPEAT.</small></div></div><div className="box-visual-foot"><span><Package size={17}/>200g PER PACK</span><span>PACKED WITH PERSONALITY</span></div></div>
    <div className="box-controls"><div className="builder-step"><span className="step-no">01</span><h3>CHOOSE YOUR BOX SIZE</h3></div><div className="box-sizes">{configs.map(b=><button className={size===b.size?'active':''} data-testid={`bundle-size-${b.size}`} key={b.size} onClick={()=>chooseSize(b.size)}><strong>{b.size}</strong><span>PACKS</span>{size===b.size&&<Check size={13}/>}</button>)}</div><div className="builder-step"><span className="step-no">02</span><h3>{bundle?.mix_match===false?'CHOOSE ONE FLAVOUR':'MAKE IT YOUR MIX'}</h3><button className="reset-button" data-testid="bundle-reset" aria-label="Clear box" onClick={()=>setSelections({})}><RotateCcw size={14}/></button></div><div className="builder-flavours">{available.map(p=><div className="builder-flavour" key={p.id}><span className="flavour-dot" style={{background:p.color}}/><div className="builder-flavour-name"><strong>{p.flavour}</strong><button data-testid={`bundle-all-${p.id}`} onClick={()=>setSelections({[p.id]:size})}>All {size}? Make it {p.flavour.toLowerCase()}.</button></div><Counter value={selections[p.id]||0} max={(selections[p.id]||0)+remaining} onChange={n=>change(p.id,n)} testId={`bundle-${p.id}`}/></div>)}</div><div className="builder-progress"><div style={{width:`${count/size*100}%`}}/></div><div className="builder-total"><span data-testid="bundle-pack-count">{count} / {size} packs selected</span><strong data-testid="bundle-price">{money(price)}</strong></div><Action disabled={count!==size} onClick={add} testId="add-box-to-cart" className="full-width">{count===size?'ADD BOX TO CART':`CHOOSE ${remaining} MORE ${remaining===1?'PACK':'PACKS'}`}</Action><p className="small-note" data-testid="bundle-price-note">{bundle?.price!=null?'Configured box price.':'Price updates with your selections.'} No mystery extras.</p></div></div>;
};
const PlusSlot=()=> <span aria-hidden="true">+</span>;