import React, {useState} from 'react';
import {Link,NavLink,useLocation} from 'react-router-dom';
import {Search,UserRound,ShoppingBag,Menu,ArrowUpRight,MessageCircle,ArrowRight} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from './ui/sheet';
import {useStore,money,track} from '../lib/store';
import {Action,Counter,Empty,Star} from './Elements';

const nav=[['SHOP','/shop'],['COMBOS','/collections/combos'],['RESELL WITH SANGLEY','/resell-with-sangley'],['OUR STORY','/our-story']];
export const Header=()=>{
  const {content,cart,setCartOpen,products}=useStore();const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState('');
  const hits=products.filter(p=>`${p.title} ${p.personality}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="announcement" data-testid="announcement-bar"><Star/><span>{content?.announcement}</span><Star/></div><header className="site-header"><div className="header-inner"><Link to="/" className="wordmark" aria-label="SANGLEY home" data-testid="header-logo">SANGLEY<span>®</span></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([name,to])=><NavLink data-testid={`nav-${to.split('/').pop()}`} key={to} to={to}>{name}{name.includes('RESELL')&&<span className="nav-dot"/>}</NavLink>)}</nav><div className="header-tools"><button aria-label="Search products" data-testid="open-search" onClick={()=>setSearch(true)}><Search size={21}/></button><Link className="account-icon" to="/account" aria-label="Your account" data-testid="open-account"><UserRound size={21}/></Link><button className="cart-trigger" aria-label="Open cart" data-testid="open-cart" onClick={()=>setCartOpen(true)}><ShoppingBag size={21}/><span data-testid="cart-count">{cart.reduce((s,x)=>s+x.quantity,0)}</span></button><button className="menu-trigger" aria-label="Open menu" data-testid="open-menu" onClick={()=>setMenu(true)}><Menu size={24}/></button></div></div></header>
    <Sheet open={menu} onOpenChange={setMenu}><SheetContent className="mobile-menu" data-testid="mobile-menu"><SheetTitle className="wordmark">SANGLEY</SheetTitle><SheetDescription>Your next crunch starts here.</SheetDescription><nav>{[...nav,['FLAVOURS','/shop'],['FAQ','/faq'],['CONTACT','/contact']].map(([name,to],i)=><Link key={`${to}-${i}`} data-testid={`mobile-nav-${i}`} to={to} onClick={()=>setMenu(false)}>{name}<ArrowUpRight/></Link>)}</nav></SheetContent></Sheet>
    <Sheet open={search} onOpenChange={setSearch}><SheetContent className="search-sheet" data-testid="search-panel"><SheetTitle>FIND YOUR CRUNCH</SheetTitle><SheetDescription>Search all four SANGLEY flavours.</SheetDescription><input autoFocus value={query} data-testid="search-input" placeholder="Try Classic, Garlic, Peri Peri…" onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')track('search',{query});}}/>{hits.map(p=><Link className="search-result" data-testid={`search-result-${p.id}`} key={p.id} to={`/products/${p.handle}`} onClick={()=>{setSearch(false);track('search',{query});}}><img src={p.images[0]} alt={p.title}/><div><strong>{p.title}</strong><p>{money(p.price)} · {p.weight}g</p></div><ArrowUpRight/></Link>)}{!hits.length&&<p data-testid="search-no-results">No crunch found. Try a different flavour.</p>}</SheetContent></Sheet>
  </>;
};
export const CartDrawer=()=>{
  const {cart,cartOpen,setCartOpen,products,updateQuantity,quote,quoteError,quoting}=useStore();
  return <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-sheet" data-testid="cart-drawer" data-lenis-prevent><SheetTitle className="drawer-heading">YOUR CRUNCH BAG<span>({cart.length})</span></SheetTitle><SheetDescription>A good break is just a few packs away.</SheetDescription>{!cart.length?<Empty title="A LITTLE TOO QUIET." description="Let’s put some crunch in here." to="/shop" cta="EXPLORE BHADANG"/>:<><div className="cart-items">{cart.map((line,i)=>{const p=products.find(p=>p.id===(line.product_id||Object.keys(line.selections||{})[0]));return <div className="cart-item" key={line.key} data-testid={`cart-item-${i}`}><img src={p?.images[0]} alt={p?.title||'SANGLEY box'}/><div className="cart-item-info"><h3 data-testid={`cart-item-${i}-title`}>{line.bundle_size?`Your ${line.bundle_size}-pack box`:p?.title||'Product unavailable'}</h3>{line.selections&&<p data-testid={`cart-item-${i}-selection`}>{Object.entries(line.selections).map(([id,n])=>`${n} ${products.find(p=>p.id===id)?.flavour||id}`).join(' · ')}</p>}<span className="cart-item-price" data-testid={`cart-item-${i}-price`}>{quote?.items[i]?money(quote.items[i].line_total):'Updating…'}</span><div className="cart-item-actions"><Counter value={line.quantity} onChange={q=>updateQuantity(line.key,q)} testId={`cart-item-${i}-quantity`}/><button className="text-link" data-testid={`cart-item-${i}-remove`} onClick={()=>updateQuantity(line.key,0)}>Remove</button></div></div></div>;})}</div><div className="cart-bottom">{quoteError&&<p role="alert" className="error-text" data-testid="cart-error">{quoteError}</p>}<Link className="cart-recommendation" to="/collections/combos" data-testid="cart-build-box" onClick={()=>setCartOpen(false)}>A box. Your rules. Explore combos <ArrowRight size={18}/></Link><div className="subtotal" data-testid="cart-subtotal"><span>Subtotal</span><strong>{quote?money(quote.subtotal):'—'}</strong></div><p className="small-note" data-testid="cart-enquiry-note">Order enquiry only. Shipping confirmed before payment.</p>{!quoteError&&<Action to={quoting?undefined:'/checkout'} disabled={quoting} className="full-width" testId="cart-checkout" onClick={()=>{if(!quoting){setCartOpen(false);track('checkout');}}}>{quoting?'UPDATING…':'CONTINUE TO ENQUIRY'}</Action>}</div></>}</SheetContent></Sheet>;
};
export const Footer=()=>{
  const {content}=useStore();
  const groups=[
    ['THE CRUNCH',[['All Bhadang','/shop'],['Our flavours','/shop'],['Build your box','/collections/combos'],['Offers','/offers']]],
    ['THE COMMUNITY',[['Resell with SANGLEY','/resell-with-sangley'],['How it works','/resell-with-sangley#how-it-works'],['Start your journey','/resell-with-sangley#join']]],
    ['THE BRAND',[['Our story','/our-story'],['FAQ','/faq'],['Contact & support','/contact']]],
    ['THE DETAILS',[['Shipping','/policies/shipping'],['Returns','/policies/returns'],['Privacy','/policies/privacy'],['Terms','/policies/terms']]]
  ];
  return <footer className="site-footer"><div className="container">
    <div className="footer-top"><div className="footer-intro"><span className="eyebrow">MAHARASHTRA-BORN. COMMUNITY-BUILT.</span><h2>GOOD CRUNCH.<br/>GREAT COMPANY.</h2><Link to="/shop" data-testid="footer-shop-cta">Come for the Bhadang. Stay for the people. <ArrowUpRight size={19}/></Link></div><Star className="footer-star"/></div>
    <div className="footer-links">{groups.map(([title,links],i)=><div key={title}><h3>{title}</h3>{links.map(([label,to],j)=><Link key={`${to}-${j}`} to={to} data-testid={`footer-link-${i}-${j}`}>{label}</Link>)}</div>)}</div>
    <div className="footer-big-word" aria-hidden="true">SANGLEY<span>®</span></div>
    <div className="footer-bottom" data-testid="footer-copyright"><span>© {new Date().getFullYear()} SANGLEY. All crunch reserved.</span><div>{content?.instagram_url&&<a data-testid="instagram-link" href={content.instagram_url} target="_blank" rel="noreferrer">INSTAGRAM ↗</a>}{content?.youtube_url&&<a data-testid="youtube-link" href={content.youtube_url} target="_blank" rel="noreferrer">YOUTUBE ↗</a>}<span>FROM SANGLI, WITH ATTITUDE.</span></div></div>
  </div></footer>;
};
export const FloatingContact=()=>{const {pathname}=useLocation();const {content}=useStore();if(pathname.startsWith('/admin')||pathname==='/checkout')return null;return <Link to="/resell-with-sangley#join" className="floating-contact" aria-label="Talk to SANGLEY" data-testid="floating-contact" onClick={e=>{if(content?.whatsapp_number){e.preventDefault();track('whatsapp_click');window.open(`https://wa.me/${content.whatsapp_number}?text=${encodeURIComponent('Hi SANGLEY, I want to know about becoming a reseller.')}`,'_blank','noopener,noreferrer');}}}><MessageCircle size={22}/><span>LET’S TALK</span></Link>;};