import React,{useEffect,useState} from 'react';
import {Routes,Route,Navigate,NavLink,Link,Outlet,useNavigate,useParams,useLocation} from 'react-router-dom';
import {LayoutDashboard,ShoppingBag,BarChart3,Package,Users,Coins,Wallet,Target,Link2,Share2,FolderOpen,Bell,LifeBuoy,UserRound,Settings,LogOut,Menu,X,ArrowUpRight,ArrowLeft,FileText,ShieldCheck,Layers,ClipboardList,Search} from 'lucide-react';
import {toast} from 'sonner';
import {api} from '../lib/store';
import {rApi,fileApi,errorText} from './api';
import {AuthProvider,useAuth,Guard,Login,Register,ApplicationStatus,ForgotPassword} from './Auth';
import {Title,PButton,Field,FormError,Empty} from './UI';
import {Dashboard,Sales,AdminDashboard} from './Dashboard';
import {Orders,OrderDetail} from './Orders';
import {Commission,Payouts} from './Finance';
import {MyLink,Toolkit} from './Sharing';
import {Targets,Notifications,Support} from './Operations';
import {Profile,ResellerSettings,Products} from './Profile';
import {Resellers,Reseller360,AuditLog} from './AdminPeople';
import {BusinessSettings,MarketingAdmin,BundleSettings,WebsiteLeads} from './AdminSettings';
import {ProductsEditor,ContentEditor} from '../components/AdminEditors';
import './portal.css';

const resellerNav=[['MY BUSINESS',[[LayoutDashboard,'Dashboard','dashboard'],[ShoppingBag,'Orders','orders'],[BarChart3,'Sales & analytics','sales'],[Package,'Products & reorder','products'],[Users,'My customers','customers']] ],['THE NUMBERS',[[Coins,'Commission','commission'],[BarChart3,'Estimated profit','profit'],[Wallet,'Payouts','payouts'],[Target,'My targets','targets']] ],['BUILD MY COMMUNITY',[[Link2,'My link & QR','my-link'],[Share2,'Share SANGLEY','share'],[FolderOpen,'Marketing toolkit','marketing-toolkit'],[Bell,'Notifications','notifications']] ],['MY CORNER',[[LifeBuoy,'Support','support'],[UserRound,'Profile','profile'],[Settings,'Settings','settings']]]];
const adminNav=[['THE COMMUNITY',[[LayoutDashboard,'Dashboard','dashboard'],[Users,'All resellers','resellers'],[ClipboardList,'Website leads','website-leads'],[ShoppingBag,'Orders','orders'],[BarChart3,'Sales & network','sales']] ],['FINANCIAL DESK',[[Coins,'Commission & rules','commission'],[Wallet,'Payout management','payouts'],[Target,'Targets','targets']] ],['THE BRAND',[[Package,'Products & pricing','products'],[Layers,'Bundles & starter kits','bundles'],[FolderOpen,'Marketing toolkit','marketing'],[Bell,'Announcements','notifications'],[FileText,'Website content','content']] ],['OPERATIONS',[[LifeBuoy,'Support desk','support'],[Settings,'Business settings','settings'],[ShieldCheck,'Audit log','audit-log']]]];

const Workspace=({admin=false,onLogout,user})=>{const [open,setOpen]=useState(false);const location=useLocation();const base=admin?'/admin/':'/reseller/';useEffect(()=>{setOpen(false);window.scrollTo(0,0);},[location.pathname]);useEffect(()=>{const onKey=e=>{if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);return <div className={`portal p-workspace ${admin?'is-admin':''}`}><aside className={`p-sidebar ${open?'open':''}`}><div className="p-sidebar-brand"><Link to="/" className="wordmark" data-testid="portal-brand-home">SANGLEY<span>®</span></Link><button className="p-sidebar-close" data-testid="close-portal-menu" aria-label="Close navigation" onClick={()=>setOpen(false)}><X size={20}/></button></div><span className="p-sidebar-kicker">{admin?'THE BUSINESS DESK':'THE COMMUNITY PORTAL'}</span><nav aria-label={admin?'Admin navigation':'Reseller navigation'}>{(admin?adminNav:resellerNav).map(([heading,links])=><div className="p-nav-group" key={heading}><span>{heading}</span>{links.map(([Icon,label,to])=><NavLink key={to} to={base+to} data-testid={`portal-nav-${to}`}><Icon size={17}/><span>{label}</span></NavLink>)}</div>)}</nav><div className="p-sidebar-foot"><span>ROOTED IN SANGLI.<br/>BUILT WITH PEOPLE.</span><button data-testid="portal-logout" onClick={onLogout}><LogOut size={17}/>SIGN OUT</button></div></aside>{open&&<button className="p-mobile-backdrop" data-testid="portal-menu-backdrop" aria-label="Close menu" onClick={()=>setOpen(false)}/>}<div className="p-main"><header className="p-topbar"><div><button className="p-menu-trigger" data-testid="open-portal-menu" aria-label="Open navigation" onClick={()=>setOpen(true)}><Menu size={23}/></button><span className="p-topbar-breadcrumb">{admin?'SANGLEY / BUSINESS DESK':'SANGLEY / MY BUSINESS'}</span></div><div className="p-topbar-actions"><Link to="/shop" className="p-store-link" data-testid="portal-view-store">VISIT THE SHOP <ArrowUpRight size={13}/></Link>{!admin&&<PButton to="/reseller/my-link" testId="portal-primary-share"><Share2 size={16}/>SHARE SANGLEY</PButton>}<div className="p-user-mark" title={user?.name} data-testid="portal-user-initial">{(user?.name||'S')[0].toUpperCase()}</div></div></header><main className="p-content"><Outlet/></main><footer className="p-workspace-footer"><span>SANGLEY COMMUNITY · REAL PEOPLE. REAL PROGRESS.</span><span>No guaranteed earnings. Just your actual business.</span></footer></div></div>;};

const ResellerWorkspace=()=>{const {auth,setAuth}=useAuth();const navigate=useNavigate();return <Workspace user={auth?.user} onLogout={async()=>{try{await rApi.post('/auth/logout');setAuth(null);navigate('/reseller/login');}catch(e){toast.error(errorText(e));}}}/>;};
const Logout=()=>{const {setAuth}=useAuth();const navigate=useNavigate();useEffect(()=>{rApi.post('/auth/logout').then(()=>{setAuth(null);navigate('/reseller/login',{replace:true});}).catch(()=>toast.error('Could not sign out. Please retry.'));},[]);return <div className="p-state">Signing out…</div>;};

export default function ResellerPortal(){return <AuthProvider><div className="portal"><Routes><Route path="register" element={<Register/>}/><Route path="login" element={<Login/>}/><Route path="forgot-password" element={<ForgotPassword/>}/><Route path="application-status" element={<ApplicationStatus/>}/><Route path="logout" element={<Logout/>}/><Route element={<Guard><ResellerWorkspace/></Guard>}><Route index element={<Navigate to="/reseller/dashboard" replace/>}/><Route path="dashboard" element={<Dashboard/>}/><Route path="orders" element={<Orders/>}/><Route path="orders/:id" element={<OrderDetail/>}/><Route path="sales" element={<Sales/>}/><Route path="products" element={<Products/>}/><Route path="customers" element={<Sales mode="customers"/>}/><Route path="commission" element={<Commission/>}/><Route path="profit" element={<Sales mode="profit"/>}/><Route path="payouts" element={<Payouts/>}/><Route path="targets" element={<Targets/>}/><Route path="my-link" element={<MyLink/>}/><Route path="share" element={<MyLink/>}/><Route path="marketing-toolkit" element={<Toolkit/>}/><Route path="notifications" element={<Notifications/>}/><Route path="support" element={<Support/>}/><Route path="profile" element={<Profile/>}/><Route path="settings" element={<ResellerSettings/>}/><Route path="*" element={<Empty title="This page isn’t in your business desk." text="Use the menu to find the right next step."/>}/></Route></Routes></div></AuthProvider>;}

export function AdminPortal(){const [user,setUser]=useState(null),[checking,setChecking]=useState(true);const navigate=useNavigate();useEffect(()=>{api.get('/auth/me').then(r=>setUser(r.data)).catch(()=>{}).finally(()=>setChecking(false));},[]);if(checking)return <div className="portal p-state">Checking protected business access…</div>;return <div className="portal"><Routes><Route path="login" element={user?<Navigate to="/admin/dashboard" replace/>:<AdminLogin onLogin={setUser}/>}/><Route element={user?<Workspace admin user={user} onLogout={async()=>{try{await api.post('/auth/logout');setUser(null);navigate('/admin/login');}catch(e){toast.error(errorText(e));}}}/>:<Navigate to="/admin/login" replace/>}><Route index element={<Navigate to="/admin/dashboard" replace/>}/><Route path="dashboard" element={<AdminDashboard/>}/><Route path="resellers" element={<Resellers/>}/><Route path="resellers/:id" element={<Reseller360/>}/><Route path="orders" element={<Orders admin/>}/><Route path="sales" element={<Sales admin/>}/><Route path="commission" element={<Commission admin/>}/><Route path="payouts" element={<Payouts admin/>}/><Route path="products" element={<><Title title="The SANGLEY catalogue" description="The existing product system, preserved. Price changes are audited."/><ProductsEditor/></>}/><Route path="bundles" element={<BundleSettings/>}/><Route path="targets" element={<Targets admin/>}/><Route path="marketing" element={<MarketingAdmin/>}/><Route path="notifications" element={<Notifications admin/>}/><Route path="support" element={<Support admin/>}/><Route path="settings" element={<BusinessSettings/>}/><Route path="audit-log" element={<AuditLog/>}/><Route path="content" element={<><Title title="The brand, in your words" description="Existing website content controls remain available."/><ContentEditor/></>}/><Route path="website-leads" element={<WebsiteLeads/>}/><Route path="*" element={<Empty title="This desk doesn’t exist." text="Use the admin navigation to find your workspace." action={false}/>}/></Route></Routes></div>;}

const AdminLogin=({onLogin})=>{const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const navigate=useNavigate();return <div className="p-admin-login"><Link to="/" className="wordmark" data-testid="admin-login-home">SANGLEY®</Link><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await api.post('/auth/login',{email,password});onLogin(r.data);navigate('/admin/dashboard');}catch(e){setError(errorText(e));}finally{setBusy(false);}}} data-testid="admin-login-form"><span className="p-eyebrow">THE BUSINESS SIDE OF THE CRUNCH</span><h1>WELCOME<br/><em>back.</em></h1><Field name="admin-email" testId="admin-email" label="EMAIL ADDRESS" type="email" value={email} onChange={setEmail} required autoComplete="username"/><Field name="admin-password" testId="admin-password" label="PASSWORD" type="password" value={password} onChange={setPassword} required autoComplete="current-password"/><FormError error={error}/><PButton type="submit" testId="admin-login-submit" disabled={busy}>{busy?'SIGNING IN…':'OPEN THE BUSINESS DESK'}<ArrowUpRight size={17}/></PButton><p className="p-caption">Protected access. Financial actions are audited.</p></form></div>;};

export function ReferralLanding(){const {code}=useParams();const navigate=useNavigate();const [error,setError]=useState('');useEffect(()=>{const p=new URLSearchParams(window.location.search);fileApi.post('/referrals/visit',{code,source:p.get('utm_source')||'referral_link',campaign:p.get('utm_campaign')||''}).then(()=>navigate('/shop'+window.location.search,{replace:true})).catch(e=>setError(errorText(e)));},[code,navigate]);return <div className="portal p-referral-landing"><span className="wordmark">SANGLEY</span>{error?<><h1>LET’S FIND YOUR CRUNCH.</h1><p data-testid="referral-error">{error}</p><PButton to="/shop" testId="invalid-referral-shop">SHOP DIRECTLY</PButton></>:<><h1>A GOOD INTRODUCTION.</h1><p data-testid="referral-validating">Checking your community link before opening the shop…</p></>}</div>;}