import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {Check,ArrowLeft,ShieldCheck} from 'lucide-react';
import {useStore,api,money,errorText,track,attribution} from '../lib/store';
import {Action,SEO,Empty,Chapter} from '../components/Elements';

export default function Checkout(){const {cart,setCart,quote,quoteError,quoting}=useStore();const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null);const [requestId]=useState(()=>{let id=sessionStorage.getItem('sangley-order-request');if(!id){id=crypto.randomUUID();sessionStorage.setItem('sangley-order-request',id);}return id;});
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(e.currentTarget));try{const r=await api.post('/orders',{...values,consent:values.consent==='on',items:cart,request_id:requestId,attribution:attribution()});setResult(r.data);let previous=[];try{previous=JSON.parse(localStorage.getItem('sangley-enquiries')||'[]');}catch{}localStorage.setItem('sangley-enquiries',JSON.stringify([{...r.data,items:cart,created_at:new Date().toISOString()},...previous].slice(0,20)));sessionStorage.removeItem('sangley-order-request');track('order_enquiry',{order_id:r.data.id,value:r.data.subtotal});setCart([]);}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  if(result)return <section className="container order-success" data-testid="order-success"><SEO title="Enquiry received"/><div className="success-seal"><Check size={35}/></div><span className="eyebrow">YOUR NEXT CRUNCH IS IN MOTION</span><h1>GOOD TASTE.<br/><span className="serif-accent">Great choice.</span></h1><p data-testid="order-confirmation-message">{result.message}</p><div className="confirmation-details"><span>YOUR ENQUIRY REFERENCE</span><strong data-testid="order-reference">{result.id}</strong><p>Product subtotal: {money(result.subtotal)}</p><p>Our team will confirm availability, delivery charges and payment arrangements. This is not a paid or confirmed order.</p></div><Action to="/shop" testId="order-continue-shopping">KEEP EXPLORING</Action><Link to="/account" className="text-link" data-testid="order-view-enquiries">View enquiries on this device</Link></section>;
  if(!cart.length)return <div className="container"><SEO title="Your order enquiry"/><Empty title="FIRST, A LITTLE CRUNCH." description="Add your favourite flavours before sending an order enquiry." to="/shop" cta="SHOP BHADANG"/></div>;
  return <section className="container checkout-page"><SEO title="Guest order enquiry"/><Link to="/shop" className="inline-action" data-testid="checkout-back"><ArrowLeft size={17}/>BACK TO THE CRUNCH</Link><Chapter number="01">NO ACCOUNT. NO FUSS.</Chapter><h1>LET’S GET YOUR<br/><span className="serif-accent">crunch sorted.</span></h1><div className="checkout-grid"><form className="checkout-form" data-testid="checkout-form" onSubmit={submit}><h2>YOUR DETAILS</h2><p>Submit an enquiry. We’ll confirm the rest with you.</p><div className="form-grid">{[['name','Full name','text','name'],['email','Email address','email','email'],['mobile','Mobile number','tel','tel'],['city','City','text','address-level2'],['address','Delivery address','text','street-address'],['pincode','PIN code','text','postal-code']].map(([name,label,type,auto])=><label className={name==='address'?'full-span':''} key={name}>{label.toUpperCase()}<input name={name} type={type} required autoComplete={auto} minLength={['name','city'].includes(name)?2:name==='address'?5:undefined} pattern={name==='mobile'?'\+?[0-9 ]{10,15}':name==='pincode'?'[1-9][0-9]{5}':undefined} inputMode={['mobile','pincode'].includes(name)?'numeric':undefined} data-testid={`checkout-${name}`} placeholder={label}/></label>)}</div><label className="consent"><input name="consent" type="checkbox" required data-testid="checkout-consent"/><span>I agree to be contacted about this enquiry. I understand no payment is being collected. <Link to="/policies/privacy" target="_blank" data-testid="checkout-privacy">Privacy information</Link></span></label>{(error||quoteError)&&<p className="error-text" role="alert" data-testid="checkout-error">{error||quoteError}</p>}<Action type="submit" className="full-width" disabled={busy||quoting||!quote||!!quoteError} testId="checkout-submit">{busy?'SENDING YOUR ENQUIRY…':'SEND ORDER ENQUIRY'}</Action><p className="small-note" data-testid="checkout-payment-note">No payment will be taken. No delivery promises until confirmed.</p></form><aside className="checkout-summary" data-testid="checkout-summary"><h2>YOUR CRUNCH COLLECTION</h2>{quote?.items.map((item,i)=><div className="checkout-line" key={i}><img src={item.image} alt={item.title}/><div><strong>{item.title}</strong><span>Quantity: {item.quantity}</span>{item.selections&&<small>{item.selections.map(s=>`${s.quantity} ${s.title}`).join(' · ')}</small>}</div><span>{money(item.line_total)}</span></div>)}{quoting&&<p data-testid="checkout-pricing-loading">Confirming current prices…</p>}<div className="subtotal" data-testid="checkout-subtotal"><span>Product subtotal</span><strong>{quote?money(quote.subtotal):'—'}</strong></div><div className="shipping-row" data-testid="checkout-shipping"><span>Shipping</span><span>Confirmed by our team</span></div><div className="checkout-note"><ShieldCheck size={23}/><p>{quote?.shipping_text||'Your enquiry will be confirmed by our team before payment.'}</p></div></aside></div></section>;
};